name: 'Tests and Coverage'
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:

jobs:
  Tests_and_Coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    name: Tests and Coverage report
    steps:
      - uses: actions/checkout@v3

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run ci:test
          working-directory: src/